/**
 * Vendor Inter into public/fonts so the app renders identically offline.
 *
 * A packaged app cannot reach fonts.googleapis.com on a plane, in a tunnel, or
 * behind a captive portal, and the request is one more thing App Review can ask
 * about. Shipping the files is simpler and faster.
 *
 * Run: node scripts/vendor-fonts.mjs
 */
import { mkdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'

const SPEC = 'family=Inter:wght@400;500;600;700'
const SUBSET = 'latin'
const OUT_DIR = join(process.cwd(), 'public', 'fonts')
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'

const css = await fetch(`https://fonts.googleapis.com/css2?${SPEC}&display=swap`, {
  headers: { 'User-Agent': UA },
}).then((r) => {
  if (!r.ok) throw new Error(`Google Fonts returned ${r.status}`)
  return r.text()
})

const blocks = [...css.matchAll(/\/\* ([\w-]+) \*\/\s*(@font-face \{[^}]*\})/g)]
  .filter(([, subset]) => subset === SUBSET)
  .map(([, , face]) => face)

if (!blocks.length) throw new Error(`No "${SUBSET}" faces found — did the CSS format change?`)

await mkdir(OUT_DIR, { recursive: true })

const rewritten = []
for (const face of blocks) {
  const url = face.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1]
  const family = face.match(/font-family: '([^']+)'/)?.[1]
  const weight = face.match(/font-weight: (\d+)/)?.[1] ?? '400'
  if (!url || !family) throw new Error(`Could not parse a face:\n${face}`)

  const name = `${family.toLowerCase().replace(/\s+/g, '-')}-${weight}.woff2`
  const bytes = Buffer.from(await fetch(url).then((r) => r.arrayBuffer()))
  await writeFile(join(OUT_DIR, name), bytes)
  console.log(`  ${name.padEnd(24)} ${(bytes.length / 1024).toFixed(1)} KB`)

  rewritten.push(face.replace(url, `/fonts/${name}`).replace(/\s+/g, ' ').trim())
}

const header =
  '/* Generated by scripts/vendor-fonts.mjs — do not edit.\n' +
  '   Bundled so the app renders identically with no network. */\n'
await writeFile(join(OUT_DIR, 'fonts.css'), `${header}${rewritten.join('\n')}\n`)
console.log(`\n${rewritten.length} faces vendored to public/fonts/`)
